### ISSUE TITLE
Regarding extrinsic evaluation

### ISSUE THREAD

**Issue by ayush1801** [gpoesia/minimo#19]
Hi Gabriel,
I ran few iterations of the `bootstrap.py` script. I wanted to confirm if the way I am doing extrinsic evaluation is fine or not:

first of all, for the figure 4. of your paper, you perform evaluation on the 10 NNG problems for the arithmetic, right?

I am using `proof_search.py` - I slightly modified the "eval" part to directly load the agent and I assign `max_mcts_nodes` and other parameters separately in the `evaluation_agent` function:
```
elif cfg.task == 'eval':
        setup_wandb(cfg)
        agent = torch.load(cfg.get("agent_path"))
        evaluate_agent(cfg,agent)
```

My config file looks like:
```
task: eval
problemset: "natural-number-game" 
end: 10
agent_path: $PATH/4.pt
job:
    wandb_project: peano
hydra:
    job:
        chdir: true
```

Is this the right way or am I missing something?
